using GameForWork.Core.P1.Progression;

namespace GameForWork.Core.P30;

internal static class P30ExplicitMasteryEffects
{
    private static readonly IReadOnlyDictionary<string, PassiveEffect[]> Rules =
        new Dictionary<string, PassiveEffect[]>(StringComparer.Ordinal)
    {
        ["暴击"] = [new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 2500), new(PassiveEffectKind.FlatAccuracy, 20), new(PassiveEffectKind.IncreasedCriticalMultiplierBasisPoints, 2500), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 3000), new(PassiveEffectKind.IncreasedCriticalMultiplierBasisPoints, 2500), new(PassiveEffectKind.IncreasedCriticalMultiplierBasisPoints, 15000), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 7500)],
        ["匕首"] = [new(PassiveEffectKind.FlatAccuracy, 50), new(PassiveEffectKind.IncreasedCriticalMultiplierBasisPoints, 10000), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 7500), new(PassiveEffectKind.IncreasedBleedDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 800), new(PassiveEffectKind.IncreasedAttackSpeedBasisPoints, 2500), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 7000)],
        ["冰缓_冻结"] = [new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 3000), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 3000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 1500), new(PassiveEffectKind.FlatMaximumMana, 5), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 800)],
        ["冰霜"] = [new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 5000), new(PassiveEffectKind.SpellSuppressionBasisPoints, 5000), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 2500), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 8000), new(PassiveEffectKind.ColdResistanceBasisPoints, 2000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 1000)],
        ["持续伤害通用"] = [new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 4000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 8000), new(PassiveEffectKind.IncreasedBleedDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedBleedDamageBasisPoints, 4000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 3000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 1000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 200)],
        ["触发_冷却"] = [new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedCooldownRecoveryBasisPoints, 2500), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 5000), new(PassiveEffectKind.FlatAccuracy, 50), new(PassiveEffectKind.IncreasedCooldownRecoveryBasisPoints, 3000), new(PassiveEffectKind.FlatMaximumMana, 20), new(PassiveEffectKind.IncreasedCooldownRecoveryBasisPoints, 3000)],
        ["锤类"] = [new(PassiveEffectKind.IncreasedAttackSpeedBasisPoints, 10000), new(PassiveEffectKind.FlatAccuracy, 30), new(PassiveEffectKind.IncreasedMaceDamageBasisPoints, 1500), new(PassiveEffectKind.IncreasedMaceDamageBasisPoints, 10000), new(PassiveEffectKind.IncreasedBleedDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 8000), new(PassiveEffectKind.FlatAccuracy, 0)],
        ["单手"] = [new(PassiveEffectKind.IncreasedOneHandDamageBasisPoints, 6000), new(PassiveEffectKind.BlockChanceBasisPoints, 3000), new(PassiveEffectKind.IncreasedSpellDamageBasisPoints, 5000), new(PassiveEffectKind.FlatAccuracy, 60), new(PassiveEffectKind.FlatAccuracy, 60), new(PassiveEffectKind.IncreasedAttackSpeedBasisPoints, 5000), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 4000)],
        ["点燃"] = [new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 3000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 7000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 6000), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 2500), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 2500), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 6000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 6000)],
        ["盾击"] = [new(PassiveEffectKind.IncreasedAttackSpeedBasisPoints, 8000), new(PassiveEffectKind.IncreasedCooldownRecoveryBasisPoints, 6000), new(PassiveEffectKind.IncreasedShieldAttackDamageBasisPoints, 1000), new(PassiveEffectKind.FlatAccuracy, 4), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 2500), new(PassiveEffectKind.IncreasedAttackSpeedBasisPoints, 700), new(PassiveEffectKind.BlockChanceBasisPoints, 6000)],
        ["法力"] = [new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 3000), new(PassiveEffectKind.FlatMaximumMana, 80), new(PassiveEffectKind.FlatMaximumMana, 20), new(PassiveEffectKind.FlatMaximumMana, 50), new(PassiveEffectKind.FlatMaximumMana, 6), new(PassiveEffectKind.FlatAccuracy, 20), new(PassiveEffectKind.FlatMaximumMana, 50)],
        ["法术"] = [new(PassiveEffectKind.IncreasedTrapDamageBasisPoints, 3500), new(PassiveEffectKind.IncreasedSpellDamageBasisPoints, 6000), new(PassiveEffectKind.FlatMaximumMana, 80), new(PassiveEffectKind.FlatMaximumMana, 30), new(PassiveEffectKind.FlatMaximumMana, 100), new(PassiveEffectKind.FlatAccuracy, 2), new(PassiveEffectKind.FlatMaximumMana, 40)],
        ["法术压制"] = [new(PassiveEffectKind.SpellSuppressionBasisPoints, 2500), new(PassiveEffectKind.SpellSuppressionBasisPoints, 2500), new(PassiveEffectKind.SpellSuppressionBasisPoints, 7000), new(PassiveEffectKind.SpellSuppressionBasisPoints, 2000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 200), new(PassiveEffectKind.SpellSuppressionBasisPoints, 3500), new(PassiveEffectKind.SpellSuppressionBasisPoints, 10000)],
        ["法杖"] = [new(PassiveEffectKind.FlatMaximumMana, 35), new(PassiveEffectKind.FlatMaximumMana, 80), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 6000), new(PassiveEffectKind.IncreasedSpellDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedSpellDamageBasisPoints, 6000), new(PassiveEffectKind.FlatAccuracy, 30), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 2000)],
        ["反击"] = [new(PassiveEffectKind.BlockChanceBasisPoints, 2500), new(PassiveEffectKind.IncreasedEvasionBasisPoints, 2500), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 1500), new(PassiveEffectKind.IncreasedCriticalMultiplierBasisPoints, 2500), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 8000), new(PassiveEffectKind.FlatAccuracy, 2), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500)],
        ["范围_距离"] = [new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 5000), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 10000), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 2500), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 2500), new(PassiveEffectKind.FlatAccuracy, 2), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 10000), new(PassiveEffectKind.FlatAccuracy, 0)],
        ["符刃"] = [new(PassiveEffectKind.IncreasedSpellDamageBasisPoints, 10000), new(PassiveEffectKind.IncreasedAttackSpeedBasisPoints, 5000), new(PassiveEffectKind.FlatAccuracy, 30), new(PassiveEffectKind.IncreasedSpellDamageBasisPoints, 10000), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 2500), new(PassiveEffectKind.SpellSuppressionBasisPoints, 2000), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 20000)],
        ["斧类"] = [new(PassiveEffectKind.IncreasedAttackSpeedBasisPoints, 6000), new(PassiveEffectKind.IncreasedAxeDamageBasisPoints, 12000), new(PassiveEffectKind.IncreasedBleedDamageBasisPoints, 6500), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 2000), new(PassiveEffectKind.IncreasedAxeDamageBasisPoints, 3000), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 6000), new(PassiveEffectKind.IncreasedAxeDamageBasisPoints, 10000)],
        ["感电_麻痹"] = [new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 1500), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 15000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 10000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 4000), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 2500)],
        ["格挡"] = [new(PassiveEffectKind.BlockChanceBasisPoints, 2500), new(PassiveEffectKind.BlockChanceBasisPoints, 2500), new(PassiveEffectKind.BlockChanceBasisPoints, 5000), new(PassiveEffectKind.BlockChanceBasisPoints, 10000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 200), new(PassiveEffectKind.BlockChanceBasisPoints, 5000), new(PassiveEffectKind.BlockChanceBasisPoints, 2500)],
        ["弓类"] = [new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 6000), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 7000), new(PassiveEffectKind.FlatMaximumMana, 3), new(PassiveEffectKind.IncreasedBowDamageBasisPoints, 2500), new(PassiveEffectKind.FlatAccuracy, 30), new(PassiveEffectKind.IncreasedBleedDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 5000)],
        ["攻击"] = [new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 4000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 4000), new(PassiveEffectKind.IncreasedAttackSpeedBasisPoints, 2500), new(PassiveEffectKind.IncreasedCooldownRecoveryBasisPoints, 6000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 3500), new(PassiveEffectKind.IncreasedTrapDamageBasisPoints, 3000), new(PassiveEffectKind.FlatAccuracy, 8)],
        ["构装体"] = [new(PassiveEffectKind.IncreasedConstructDamageBasisPoints, 1500), new(PassiveEffectKind.IncreasedConstructDamageBasisPoints, 4000), new(PassiveEffectKind.IncreasedConstructDamageBasisPoints, 3000), new(PassiveEffectKind.IncreasedConstructDamageBasisPoints, 10000), new(PassiveEffectKind.IncreasedConstructDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 2000), new(PassiveEffectKind.IncreasedConstructDamageBasisPoints, 2500)],
        ["光环_保留"] = [new(PassiveEffectKind.IncreasedAuraEffectBasisPoints, 5000), new(PassiveEffectKind.IncreasedAuraEffectBasisPoints, 6000), new(PassiveEffectKind.IncreasedAuraEffectBasisPoints, 5000), new(PassiveEffectKind.IncreasedAuraEffectBasisPoints, 10000), new(PassiveEffectKind.FlatMaximumMana, 1), new(PassiveEffectKind.FlatMaximumMana, 3), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 3000)],
        ["护甲"] = [new(PassiveEffectKind.IncreasedArmorBasisPoints, 6000), new(PassiveEffectKind.FlatDexterity, 20), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 3000), new(PassiveEffectKind.FlatAccuracy, 50), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 2000), new(PassiveEffectKind.IncreasedArmorBasisPoints, 5000), new(PassiveEffectKind.IncreasedArmorBasisPoints, 400)],
        ["护体_承伤缓冲"] = [new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedSpellDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedArmorBasisPoints, 300), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 10000), new(PassiveEffectKind.IncreasedCooldownRecoveryBasisPoints, 6000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 5000), new(PassiveEffectKind.FlatMaximumMana, 20)],
        ["幻身"] = [new(PassiveEffectKind.IncreasedSpellDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 6000), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 2500), new(PassiveEffectKind.IncreasedCooldownRecoveryBasisPoints, 2000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 4000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 3000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 5000)],
        ["火焰"] = [new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 8000), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 2500), new(PassiveEffectKind.FireResistanceBasisPoints, 2000), new(PassiveEffectKind.FireResistanceBasisPoints, 1000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 500)],
        ["伙伴"] = [new(PassiveEffectKind.IncreasedCompanionDamageBasisPoints, 4000), new(PassiveEffectKind.IncreasedCompanionDamageBasisPoints, 3000), new(PassiveEffectKind.IncreasedCompanionDamageBasisPoints, 3000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 7500), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 5000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 3000), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 2500)],
        ["剑类"] = [new(PassiveEffectKind.IncreasedCriticalMultiplierBasisPoints, 8000), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 2000), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 4000), new(PassiveEffectKind.BlockChanceBasisPoints, 800), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 4000), new(PassiveEffectKind.IncreasedBleedDamageBasisPoints, 2000), new(PassiveEffectKind.FlatAccuracy, 5)],
        ["近战打击"] = [new(PassiveEffectKind.FlatAccuracy, 2), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 3500), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 6000), new(PassiveEffectKind.FlatAccuracy, 50), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 10000)],
        ["灵障"] = [new(PassiveEffectKind.IncreasedShieldBasisPoints, 5000), new(PassiveEffectKind.IncreasedShieldBasisPoints, 3000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 1500), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 10000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 150), new(PassiveEffectKind.IncreasedShieldBasisPoints, 8000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 800)],
        ["流血"] = [new(PassiveEffectKind.IncreasedBleedDamageBasisPoints, 10000), new(PassiveEffectKind.IncreasedBleedDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedBleedDamageBasisPoints, 3500), new(PassiveEffectKind.IncreasedBleedDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedBleedDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedBleedDamageBasisPoints, 6000), new(PassiveEffectKind.IncreasedBleedDamageBasisPoints, 300)],
        ["美德_恶德"] = [new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 15000), new(PassiveEffectKind.IncreasedCurseEffectBasisPoints, 2500), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 2500)],
        ["命中_精准"] = [new(PassiveEffectKind.FlatAccuracy, 1000), new(PassiveEffectKind.FlatAccuracy, 1000), new(PassiveEffectKind.FlatAccuracy, 1000), new(PassiveEffectKind.FlatAccuracy, 100), new(PassiveEffectKind.FlatAccuracy, 15), new(PassiveEffectKind.FlatAccuracy, 4), new(PassiveEffectKind.FlatAccuracy, 30)],
        ["能量护盾"] = [new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 4000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 1500), new(PassiveEffectKind.IncreasedShieldBasisPoints, 200), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 2000), new(PassiveEffectKind.IncreasedShieldBasisPoints, 2000), new(PassiveEffectKind.FlatMaximumMana, 80), new(PassiveEffectKind.FlatMaximumMana, 50)],
        ["破甲_物理穿透"] = [new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 10000), new(PassiveEffectKind.IncreasedSpellDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedArmorBasisPoints, 5000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 6000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 3000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 0)],
        ["普通召唤物"] = [new(PassiveEffectKind.IncreasedMinionDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedMinionDamageBasisPoints, 3500), new(PassiveEffectKind.IncreasedMinionDamageBasisPoints, 4000), new(PassiveEffectKind.IncreasedMinionDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedMinionDamageBasisPoints, 3000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 500), new(PassiveEffectKind.IncreasedMinionDamageBasisPoints, 3500)],
        ["侵蚀_凋零"] = [new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 20000), new(PassiveEffectKind.FlatMaximumMana, 5), new(PassiveEffectKind.IncreasedVoidDamageBasisPoints, 4000), new(PassiveEffectKind.SpellSuppressionBasisPoints, 1500)],
        ["闪避"] = [new(PassiveEffectKind.IncreasedArmorBasisPoints, 6000), new(PassiveEffectKind.FlatDexterity, 4), new(PassiveEffectKind.IncreasedEvasionBasisPoints, 9500), new(PassiveEffectKind.IncreasedEvasionBasisPoints, 3500), new(PassiveEffectKind.IncreasedEvasionBasisPoints, 10000), new(PassiveEffectKind.IncreasedEvasionBasisPoints, 4000), new(PassiveEffectKind.IncreasedEvasionBasisPoints, 2500)],
        ["闪电"] = [new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 5000), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 6000), new(PassiveEffectKind.IncreasedSpellDamageBasisPoints, 10000), new(PassiveEffectKind.LightningResistanceBasisPoints, 2000), new(PassiveEffectKind.LightningResistanceBasisPoints, 1000)],
        ["生命"] = [new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 3000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 4000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 1500), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 4000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 500), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 1000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 2000)],
        ["属性"] = [new(PassiveEffectKind.FlatPhysique, 50), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 3000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 3000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 3000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 500)],
        ["双持"] = [new(PassiveEffectKind.IncreasedAttackSpeedBasisPoints, 2500), new(PassiveEffectKind.IncreasedCriticalMultiplierBasisPoints, 2500), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 5000), new(PassiveEffectKind.BlockChanceBasisPoints, 6000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 10000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 100), new(PassiveEffectKind.FlatAccuracy, 4)],
        ["双手"] = [new(PassiveEffectKind.IncreasedAttackSpeedBasisPoints, 10000), new(PassiveEffectKind.IncreasedTwoHandDamageBasisPoints, 6000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 7000), new(PassiveEffectKind.IncreasedTwoHandDamageBasisPoints, 4000), new(PassiveEffectKind.IncreasedTwoHandDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedArmorBasisPoints, 4000), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 300)],
        ["偷取"] = [new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 300), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 3000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 2500), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 6000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 3000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 1500), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 5000)],
        ["投射物"] = [new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 5000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2000), new(PassiveEffectKind.FlatAccuracy, 2), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 1000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 4000), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 5000), new(PassiveEffectKind.FlatAccuracy, 25)],
        ["徒手"] = [new(PassiveEffectKind.IncreasedUnarmedDamageBasisPoints, 6000), new(PassiveEffectKind.FlatPhysique, 10), new(PassiveEffectKind.IncreasedUnarmedDamageBasisPoints, 3500), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 6000), new(PassiveEffectKind.IncreasedUnarmedDamageBasisPoints, 400), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 500), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 8000)],
        ["物理"] = [new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 6000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 10000), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 1000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 1000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 3500)],
        ["陷阱"] = [new(PassiveEffectKind.IncreasedTrapDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 5000), new(PassiveEffectKind.IncreasedTrapDamageBasisPoints, 1500), new(PassiveEffectKind.IncreasedTrapDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedTrapDamageBasisPoints, 3000), new(PassiveEffectKind.IncreasedTrapDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 2000)],
        ["虚空"] = [new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 5000), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 5000), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 8000), new(PassiveEffectKind.VoidResistanceBasisPoints, 2000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 1000)],
        ["虚空抗性"] = [new(PassiveEffectKind.VoidResistanceBasisPoints, 2500), new(PassiveEffectKind.VoidResistanceBasisPoints, 2500), new(PassiveEffectKind.IncreasedShieldBasisPoints, 600), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 2500), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 200), new(PassiveEffectKind.IncreasedVoidDamageBasisPoints, 4000), new(PassiveEffectKind.VoidResistanceBasisPoints, 1500)],
        ["眩晕"] = [new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 4000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 15000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 3500), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500), new(PassiveEffectKind.SpellSuppressionBasisPoints, 2000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500)],
        ["药剂"] = [new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 4000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 2500), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 4000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 3000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 500), new(PassiveEffectKind.IncreasedCooldownRecoveryBasisPoints, 2500), new(PassiveEffectKind.IncreasedArmorBasisPoints, 3000)],
        ["元素抗性"] = [new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedArmorBasisPoints, 400), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 1500), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 4000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 2000), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 1000)],
        ["元素曝露_元素穿透"] = [new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 10000), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 1500), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 20000), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 2500), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 0), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, -5000)],
        ["元素通用"] = [new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 4000), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 3000), new(PassiveEffectKind.IncreasedSpellDamageBasisPoints, 4000), new(PassiveEffectKind.FlatMaximumMana, 0), new(PassiveEffectKind.IncreasedElementalDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 4000), new(PassiveEffectKind.LightningResistanceBasisPoints, 2500)],
        ["再生_持续恢复"] = [new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 5000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 6000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 3000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 4000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 6000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 5000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 10000)],
        ["战吼_增益"] = [new(PassiveEffectKind.IncreasedCooldownRecoveryBasisPoints, 4000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 6000), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 6000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 10000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 4000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 1500)],
        ["中毒"] = [new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 6000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 10000), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 7000), new(PassiveEffectKind.IncreasedCriticalChanceBasisPoints, 2500), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 2500), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 1500), new(PassiveEffectKind.IncreasedDamageOverTimeBasisPoints, 10000)],
        ["重复_引导"] = [new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 10000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500), new(PassiveEffectKind.IncreasedSkillRangeBasisPoints, 3000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 5000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 1500), new(PassiveEffectKind.IncreasedCooldownRecoveryBasisPoints, 10000), new(PassiveEffectKind.IncreasedAttackSkillDamageBasisPoints, 2500)],
        ["诅咒"] = [new(PassiveEffectKind.IncreasedCurseEffectBasisPoints, 2000), new(PassiveEffectKind.IncreasedCurseEffectBasisPoints, 5000), new(PassiveEffectKind.IncreasedCurseEffectBasisPoints, 2500), new(PassiveEffectKind.IncreasedCurseEffectBasisPoints, 1500), new(PassiveEffectKind.IncreasedCurseEffectBasisPoints, 5000), new(PassiveEffectKind.IncreasedMaximumLifeBasisPoints, 2500), new(PassiveEffectKind.IncreasedCurseEffectBasisPoints, 1500)],
    };

    public static PassiveEffect Get(string masteryKey, int option)
    {
        if (!Rules.TryGetValue(masteryKey, out PassiveEffect[]? effects) || option < 0 || option >= effects.Length)
            throw new InvalidDataException($"Missing explicit mastery effect: {masteryKey}[{option}].");
        return Corrected(masteryKey, option, effects[option]);
    }

    public static int RuleCount => Rules.Sum(pair => pair.Value.Length);

    private static PassiveEffect Corrected(string key, int option, PassiveEffect fallback) => (key, option) switch
    {
        ("双手", 0) or ("双手", 2) or ("剑类", 6) or ("属性", 3) or
        ("近战打击", 2) or ("破甲_物理穿透", 1) or ("眩晕", 1) or
        ("护体_承伤缓冲", 0) or ("偷取", 0) or ("双手", 5) or
        ("生命", 0) or ("生命", 3) or ("能量护盾", 0) or ("能量护盾", 1) or
        ("法力", 2) or ("护甲", 0) or ("闪避", 0) or ("闪避", 3) or
        ("攻击", 0) or ("斧类", 0) or ("单手", 0) => new(fallback.Kind, 0),
        _ => fallback,
    };
}
